DROP TABLE "LIKE";
DROP TABLE "RE";
DROP TABLE "CONTENT";
DROP TABLE "USERS";
DROP TABLE "FOLLOW";
DROP TABLE "SAVE_CONTENT";
DROP TABLE "LIVE_USER";
DROP TABLE OPENCHATLIST;
DROP TABLE MYOPENCHAT;
DROP TABLE DMLIST;


DROP SEQUENCE USERS_NO;
DROP SEQUENCE CONTENT_NO;
DROP SEQUENCE RE_NO;
DROP SEQUENCE DM_NO;

CREATE SEQUENCE USERS_NO NOCACHE;
CREATE SEQUENCE CONTENT_NO NOCACHE;
CREATE SEQUENCE RE_NO NOCACHE;
CREATE SEQUENCE DM_NO NOCACHE;

CREATE TABLE "USERS" (
	"USERS_NO"	NUMBER				NOT NULL,
	"USERS_ID"	VARCHAR2(4000)		UNIQUE NOT NULL,
	"USERS_NICKNAME" VARCHAR2(4000) UNIQUE NOT NULL,
	"USERS_PW"	VARCHAR2(4000)		NOT NULL,
	"USERS_NAME"	VARCHAR2(4000)	NOT	NULL,
	"USERS_PHONE"	VARCHAR2(4000)	UNIQUE NOT	NULL,
	"USERS_PROFILE"	VARCHAR2(4000)	NOT	NULL,
	"USER_INFO"	VARCHAR2(4000) DEFAULT '입력하세요'
);


CREATE TABLE "CONTENT" (
   "CONTENT_NO"   NUMBER            NOT NULL,
   "CONTENT_PHOTO"   VARCHAR2(4000)      NOT   NULL,
   "CONTENT_SUBSTANCE"   VARCHAR2(4000)   NOT NULL,
   "CONTENT_PLACE_NAME" VARCHAR2(4000)   NOT NULL,
   "CONTENT_PLACE_LAT" VARCHAR2(4000)   NOT NULL,
   "CONTENT_PLACE_LON" VARCHAR2(4000)   NOT NULL,
   "CONTENT_USERS_ID"   VARCHAR2(4000)      NOT NULL,
   "CONTENT_COMMENT_COUNT" NUMBER   NOT NULL,
   "CONTENT_LIKE_COUNT"    NUMBER NOT NULL,
   "CONTENT_HASHTAG" VARCHAR2(4000),
   "CONTENT_DATE" DATE NOT NULL
);

CREATE TABLE "RE" (
	"RE_NO"	NUMBER						NOT NULL,
	"RE_SUBSTANCE"	VARCHAR2(4000)		NOT	NULL,
	"RE_CONTENT_NO"	NUMBER				NOT NULL,
	"RE_USERS_ID"	VARCHAR2(4000)		NOT NULL
);


CREATE TABLE "LIKE" (
	"LIKE_CONTENT_NO"	NUMBER			NOT NULL,
	"LIKE_USERS_ID"	 VARCHAR2(4000)		NOT NULL,
	"LIKE_LIKED"	VARCHAR2(4000)		NOT NULL
);

CREATE TABLE "FOLLOW"(
	"FOLLOW_ID" VARCHAR2(400) NOT NULL,
	"FOLLOW_TARGET" VARCHAR2(400) NOT NULL
);

CREATE TABLE "SAVE_CONTENT" (
   "SAVE_CONTENT_NO"   NUMBER            NOT NULL,
   "SAVE_CONTENT_PHOTO"   VARCHAR2(4000)      NOT   NULL,
   "SAVE_CONTENT_SUBSTANCE"   VARCHAR2(4000)   NOT NULL,
   "SAVE_CONTENT_PLACE_NAME" VARCHAR2(4000)   NOT NULL,
   "SAVE_CONTENT_PLACE_LAT" VARCHAR2(4000)   NOT NULL,
   "SAVE_CONTENT_PLACE_LON" VARCHAR2(4000)   NOT NULL,
   "SAVE_CONTENT_USERS_ID"   VARCHAR2(4000)      NOT NULL,
   "SAVE_CONTENT_HASHTAG" VARCHAR2(4000),
   "SAVE_CONTENT_DATE" DATE NOT NULL,
	"SAVE_USER_ID" VARCHAR2(4000) NOT NULL,
	"SAVE_DATE" DATE NOT NULL
);

CREATE TABLE LIVE_USER (
	LIVE_USER_ID VARCHAR2(4000) UNIQUE NOT NULL,
	LIVE_START_TIME DATE NOT NULL,
	LIVE_USER_PROFILE VARCHAR2(4000) NOT NULL
);

CREATE TABLE OPENCHATLIST (
	OPENCHAT_NAME VARCHAR2(4000)  UNIQUE NOT NULL,
	OPENCHAT_PW VARCHAR2(4000) ,
	OPENCHAT_LIMIT VARCHAR2(4000) NOT NULL
);

CREATE TABLE MYOPENCHAT (
	MYOPENCHAT_NAME VARCHAR2(4000) NOT NULL,
	MYOPENCHAT_USERID VARCHAR2(4000) NOT NULL
);

CREATE TABLE DMLIST(
	DM_NO NUMBER NOT NULL,
	DM_USER_ID VARCHAR2(4000) NOT NULL,
	DM_RECEIVER VARCHAR2(4000) NOT NULL,
	DM_STATUS VARCHAR2(4000) NOT NULL,
	DM_DATE DATE NOT NULL
);

ALTER TABLE "FOLLOW" ADD CONSTRAINT "PK_FOLLOW" PRIMARY KEY (
	"FOLLOW_ID",
	"FOLLOW_TARGET"
);

ALTER TABLE "USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY (
	"USERS_NO"
);

ALTER TABLE "CONTENT" ADD CONSTRAINT "PK_CONTENT" PRIMARY KEY (
	"CONTENT_NO"
);

ALTER TABLE "RE" ADD CONSTRAINT "PK_RE" PRIMARY KEY (
	"RE_NO"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "PK_LIKE" PRIMARY KEY (
	"LIKE_CONTENT_NO",
	"LIKE_USERS_ID"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "FK_CONTENT_TO_LIKE_1" FOREIGN KEY (
	"LIKE_CONTENT_NO"
)
REFERENCES "CONTENT" (
	"CONTENT_NO"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "FK_USER_TO_LIKE_1" FOREIGN KEY (
	"LIKE_USERS_ID"
)
REFERENCES "USERS" (
	"USERS_ID"
);

select * from DMLIST;
delete DMLIST;
select * from OPENCHATLIST;

insert into DMLIST values('1', 'user1', 'user2', 'Y', SYSDATE);
insert into DMLIST values('1', 'user2', 'user1', 'Y', SYSDATE);
select * from DMLIST where DM_USER_ID = 'user2' and dm_status = 'N';
update DMLIST set DM_STATUS = 'N' where DM_USER_ID = 'user2' and DM_RECEIVER = 'user1';

SELECT DM_STATUS FROM DMLIST WHERE DM_RECEIVER = 'user2' AND DM_NO = '1';

select * from USERS;

select * from LIVE_USER;

